name: Build GP

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*
jobs:
  build:
    name: Release build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Build split apk
        run: |
          flutter pub get
          flutter build apk --target-platform android-arm64,android-x64 --split-per-abi --release --dart-define=APP_CHANNEL=play --tree-shake-icons
          ls build/app/outputs/flutter-apk
      - name: Sign build apk
        uses: iota9star/sign-android-release@v1.0.5
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          fileRegex: .*-release.apk
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"
      - name: Upload signed apk
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: build/app/outputs/flutter-apk/
      - name: Release to GP
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: io.nichijou.flutter.mikan
          releaseFiles: 'build/app/outputs/flutter-apk/*-release-signed.apk'
          track: production
          inAppUpdatePriority: 5
          status: draft
          mappingFile: build/app/outputs/mapping/release/mapping.txt
